---
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
- 2.1.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.5.1"
    - PUPPET_GEM_VERSION="~> 3.6.2"
    - PUPPET_GEM_VERSION="~> 3.7.5"
matrix:
  exclude:
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.2.4"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.3.2"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4.3"
notification:
  email: false
addons:
  code_climate:
    repo_token: 5Zl6r5FTDCU6uJmAy43YVAN2t8Z7cn5PO
